### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by kreja** [Darmody/Gecko#2]
# UI design

This is the preliminary ui design. We will choose one from the following three styles, and then optimize the details. Please let me know if you have any questions or concerns. Thanks.
## the basic structure
- slide from the right side of the screen
  ![1](https://cloud.githubusercontent.com/assets/7478555/10868356/6fb9118c-80c7-11e5-9ad2-ec7699c8c99e.png)
-  drop down from the top side of the screen
  ![2](https://cloud.githubusercontent.com/assets/7478555/10868401/8baf986a-80c8-11e5-8eb4-1869095e0b2b.png)
## fasion style with big background

![v3-1](https://cloud.githubusercontent.com/assets/7478555/10868405/a25f5bea-80c8-11e5-9142-07618e04d975.png)
![v3-2](https://cloud.githubusercontent.com/assets/7478555/10868408/c1da9354-80c8-11e5-8ef7-9f01a9c318f4.png)
## fresh style

![v4-1](https://cloud.githubusercontent.com/assets/7478555/10868410/d0422b64-80c8-11e5-9b98-09f59e640f6d.png)
![v4-2](https://cloud.githubusercontent.com/assets/7478555/10868411/d32377a2-80c8-11e5-963b-a9acc3390ba8.png)
![v4-3](https://cloud.githubusercontent.com/assets/7478555/10868412/d535e818-80c8-11e5-8970-70a79708e710.png)
## flat style

![v5-1](https://cloud.githubusercontent.com/assets/7478555/10868413/df16e54e-80c8-11e5-8171-c39c65112367.png)
![v5-2](https://cloud.githubusercontent.com/assets/7478555/10868414/e0fa80b4-80c8-11e5-8922-e9f3e5b578e2.png)
![v5-3](https://cloud.githubusercontent.com/assets/7478555/10868415/e27de1b0-80c8-11e5-84ff-746882575b77.png)

**Comment by Darmody** [comment]
Awesome! I think `flat style` is my favorite. :100:

**Comment by Darmody** [comment]
@kreja how about color schemes below?
![gecko2](https://cloud.githubusercontent.com/assets/6788752/10869280/530a1ae0-80e5-11e5-8bad-66ec65bfb224.png)
![gecko1](https://cloud.githubusercontent.com/assets/6788752/10869284/556c2cf6-80e5-11e5-8b39-ed65912ccea9.png)

**Comment by Darmody** [comment]
And i have an idea. We can hide the footer tabs which will show when hovering.That simplify UI more.

**Comment by Darmody** [comment]
Because of the philosophy of this project has been changed, ui may not be a necessary part.

**Comment by kreja** [comment]
Looks like twitter...

**Comment by Darmody** [comment]
UI become a necessary part of the project again!

**Comment by kreja** [comment]
Congratulations!
I like the fashion style with big background.

**Comment by Darmody** [comment]
Finally, I decide to setup ui like this:

![image](https://cloud.githubusercontent.com/assets/6788752/11606205/911e850e-9b53-11e5-97b4-3817014af4ea.png)

**Comment by kreja** [comment]
Good job!
